### PR TITLE
Updating bootstrap to v4.0.0

### PR DESCRIPTION
**Pull request by dushkostanoeski**
Upgraded bootstrap to  v4.0.0-beta2. I didn't add the `popper.js` dependency because it is included in the `bootstrap.bundle.min.js` that is used, but it will still give out a warning when installing the packages.

### CODE REVIEW

**Comment by dushkostanoeski** [comment]
And sorry about the mess :)

**Comment by FabianGosebrink** [comment]
Spoke to @damienbod: Can we wait until bootstrap 4 is finally released? We will merge it then. BR

**Comment by dushkostanoeski** [comment]
OK, I'll keep this branch updated with the latest bootstrap betas for people that want to make the switch.

**Comment by FabianGosebrink** [comment]
Amazing, thank you :)

**Pull request merged**
